//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/PetInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PetInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PetInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PetInputActions"",
    ""maps"": [
        {
            ""name"": ""DesktopPet"",
            ""id"": ""b7ad0ede-bd21-427d-87d6-fe29db67bb95"",
            ""actions"": [
                {
                    ""name"": ""Point"",
                    ""type"": ""Value"",
                    ""id"": ""71dbb5bd-3303-4e3b-bc0d-0a91ddcd0803"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""091380e9-2c7e-4ec5-a033-a508aa1b6420"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5673c6e2-84e5-4cc7-97ec-93ab93216327"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""135eb08b-547a-46e6-9691-6e2d7c58827c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DesktopPet
        m_DesktopPet = asset.FindActionMap("DesktopPet", throwIfNotFound: true);
        m_DesktopPet_Point = m_DesktopPet.FindAction("Point", throwIfNotFound: true);
        m_DesktopPet_LeftClick = m_DesktopPet.FindAction("LeftClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DesktopPet
    private readonly InputActionMap m_DesktopPet;
    private List<IDesktopPetActions> m_DesktopPetActionsCallbackInterfaces = new List<IDesktopPetActions>();
    private readonly InputAction m_DesktopPet_Point;
    private readonly InputAction m_DesktopPet_LeftClick;
    public struct DesktopPetActions
    {
        private @PetInputActions m_Wrapper;
        public DesktopPetActions(@PetInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Point => m_Wrapper.m_DesktopPet_Point;
        public InputAction @LeftClick => m_Wrapper.m_DesktopPet_LeftClick;
        public InputActionMap Get() { return m_Wrapper.m_DesktopPet; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DesktopPetActions set) { return set.Get(); }
        public void AddCallbacks(IDesktopPetActions instance)
        {
            if (instance == null || m_Wrapper.m_DesktopPetActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DesktopPetActionsCallbackInterfaces.Add(instance);
            @Point.started += instance.OnPoint;
            @Point.performed += instance.OnPoint;
            @Point.canceled += instance.OnPoint;
            @LeftClick.started += instance.OnLeftClick;
            @LeftClick.performed += instance.OnLeftClick;
            @LeftClick.canceled += instance.OnLeftClick;
        }

        private void UnregisterCallbacks(IDesktopPetActions instance)
        {
            @Point.started -= instance.OnPoint;
            @Point.performed -= instance.OnPoint;
            @Point.canceled -= instance.OnPoint;
            @LeftClick.started -= instance.OnLeftClick;
            @LeftClick.performed -= instance.OnLeftClick;
            @LeftClick.canceled -= instance.OnLeftClick;
        }

        public void RemoveCallbacks(IDesktopPetActions instance)
        {
            if (m_Wrapper.m_DesktopPetActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDesktopPetActions instance)
        {
            foreach (var item in m_Wrapper.m_DesktopPetActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DesktopPetActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DesktopPetActions @DesktopPet => new DesktopPetActions(this);
    public interface IDesktopPetActions
    {
        void OnPoint(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
    }
}
